# Generated by Django 3.2.10 on 2021-12-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='college',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='qualification',
        ),
        migrations.AddField(
            model_name='faculty',
            name='department',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Science'), ('CS&IT', 'Computer Science and IT'), ('IT', 'IT'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('EE', 'Electrical and Electronics'), ('Humanities', 'Humanities'), ('Others', 'Any other')], max_length=10, null=True),
        ),
    ]
