# Generated by Django 3.2.10 on 2022-01-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0003_auto_20220122_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='profile_pic_firebase',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
