# Generated by Django 3.2.10 on 2022-01-09 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('no_of_question', models.IntegerField()),
                ('time_limit', models.IntegerField(blank=True, null=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_faculty', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=150)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='Quiz.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=80)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='Quiz.quizquestion')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_option_text', models.CharField(blank=True, max_length=80, null=True)),
                ('correct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_option', to='Quiz.option')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct', to='Quiz.quizquestion')),
            ],
        ),
    ]
