# Generated by Django 3.2.10 on 2022-01-14 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctoption',
            name='correct_option_text',
        ),
    ]
