# Generated by Django 3.2.10 on 2022-01-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_alter_quiz_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='banner_firebase',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
