# Generated by Django 3.2.10 on 2022-01-25 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_quiz_banner_firebase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-id']},
        ),
    ]
