# Generated by Django 3.2.10 on 2022-01-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-likes']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-commented']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-raised']},
        ),
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
