# Generated by Django 3.2.10 on 2022-01-04 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Forum', '0002_auto_20220103_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='likes',
        ),
        migrations.CreateModel(
            name='LikeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='Forum.answer')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
