# Generated by Django 3.2.10 on 2022-01-22 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Forum', '0003_auto_20220104_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark_question_id', to='Forum.question')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bookmark_question', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
