# Generated by Django 3.2.10 on 2022-01-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0004_bookmarkquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likeanswer',
            name='likes',
        ),
        migrations.AddField(
            model_name='likeanswer',
            name='like',
            field=models.BooleanField(default=1),
        ),
    ]
