# Generated by Django 3.2.10 on 2022-01-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_obj',
            field=models.FileField(upload_to='Note_files'),
        ),
    ]
