# Generated by Django 3.2.10 on 2022-01-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0005_alter_file_file_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file_obj_firebase',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
