# Generated by Django 3.2.10 on 2022-01-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic_firebase',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
