# Generated by Django 3.2.10 on 2022-01-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_student_profile_pic_firebase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='interest',
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=8, null=True),
        ),
    ]
